name: Tinder Api Build

on:
  push:
    branches:
      - release/*

jobs:
  build:
    name: Build Release Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew buildReleaseAndBumpValues
      - name: Upload Jar
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: build/libs/*.jar


  release:
    name: Release Jar
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Previous tag
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Download Jar from build
        uses: actions/download-artifact@v1
        with:
          name: jar
          path: ./
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ steps.previous_tag.outputs.tag }}
          release_name: Release ${{ steps.previous_tag.outputs.tag }}
      - name: Upload Release Jar
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ITindr-Api-${{ steps.previous_tag.outputs.tag }}.jar
          asset_name: ITindr-Api-${{ steps.previous_tag.outputs.tag }}.jar
          asset_content_type: application/zip

  deploy:
    name: Deploy to server
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Jar from build
        uses: actions/download-artifact@v1
        with:
          name: jar
          path: ./
      - name: Stop and remove previous build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: ${{ secrents.STOP_SCRIPT }}
      - name: Copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "*.jar"
          target: ${{ secrets.APP_DIR }}
      - name: Run new build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: ${{ secrets.RUN_SCRIPT }}
